# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

openapi: 3.0.1
tags:
  - description:
      "The public API of the Data Plane is a data proxy enabling a data consumer\
      \ to actively querydata from the provider data source (e.g. backend Rest API,\
      \ internal database...) through its Data Planeinstance. Thus the Data Plane is\
      \ the only entry/output door for the data, which avoids the provider to exposedirectly\
      \ its data externally.The Data Plane public API being a proxy, it supports all\
      \ verbs (i.e. GET, POST, PUT, PATCH, DELETE), whichcan then conveyed until the\
      \ data source is required. This is especially useful when the actual data sourceis\
      \ a Rest API itself.In the same manner, any set of arbitrary query parameters,\
      \ path parameters and request body are supported (in the limits fixed by the HTTP\
      \ server) and can also conveyed to the actual data source."
    name: Data Plane public API
paths:
  /{any}:
    delete:
      description: Send `DELETE` data query to the Data Plane.
      operationId: delete
      responses:
        "400":
          description: Missing access token
        "403":
          description: Access token is expired or invalid
        "500":
          description: Failed to transfer data
      tags:
        - Data Plane public API
      x-amazon-apigateway-integration:
        type: http_proxy
        httpMethod: DELETE
        connectionId: "${vpcLinkId}"
        connectionType: VPC_LINK
        uri: http://${loadBalancerDnsName}/api/public/{any}
    get:
      description: Send `GET` data query to the Data Plane.
      operationId: get
      responses:
        "400":
          description: Missing access token
        "403":
          description: Access token is expired or invalid
        "500":
          description: Failed to transfer data
      tags:
        - Data Plane public API
      x-amazon-apigateway-integration:
        type: http_proxy
        httpMethod: GET
        requestParameters:
          integration.request.path.any: method.request.path.any
        connectionId: "${vpcLinkId}"
        connectionType: VPC_LINK
        uri: http://${loadBalancerDnsName}/api/public/{any}
    head:
      description: Send `HEAD` data query to the Data Plane.
      operationId: head
      responses:
        "400":
          description: Missing access token
        "403":
          description: Access token is expired or invalid
        "500":
          description: Failed to transfer data
      tags:
        - Data Plane public API
      x-amazon-apigateway-integration:
        type: http_proxy
        httpMethod: HEAD
        connectionId: "${vpcLinkId}"
        connectionType: VPC_LINK
        uri: http://${loadBalancerDnsName}/api/public/{any}
    patch:
      description: Send `PATCH` data query to the Data Plane.
      operationId: patch
      responses:
        "400":
          description: Missing access token
        "403":
          description: Access token is expired or invalid
        "500":
          description: Failed to transfer data
      tags:
        - Data Plane public API
      x-amazon-apigateway-integration:
        type: http_proxy
        httpMethod: PATCH
        connectionId: "${vpcLinkId}"
        connectionType: VPC_LINK
        uri: http://${loadBalancerDnsName}/api/public/{any}
    post:
      description: Send `POST` data query to the Data Plane.
      operationId: post
      responses:
        "400":
          description: Missing access token
        "403":
          description: Access token is expired or invalid
        "500":
          description: Failed to transfer data
      tags:
        - Data Plane public API
      x-amazon-apigateway-integration:
        type: http_proxy
        httpMethod: POST
        connectionId: "${vpcLinkId}"
        connectionType: VPC_LINK
        uri: http://${loadBalancerDnsName}/api/public/{any}
    put:
      description: Send `PUT` data query to the Data Plane.
      operationId: put
      responses:
        "400":
          description: Missing access token
        "403":
          description: Access token is expired or invalid
        "500":
          description: Failed to transfer data
      tags:
        - Data Plane public API
      x-amazon-apigateway-integration:
        type: http_proxy
        httpMethod: PUT
        connectionId: "${vpcLinkId}"
        connectionType: VPC_LINK
        uri: http://${loadBalancerDnsName}/api/public/{any}
