# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

openapi: 3.0.1
paths:
  /check/health:
    get:
      description:
        Performs a liveness probe to determine whether the runtime is working
        properly.
      operationId: checkHealth
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthStatus"
          description: The runtime is working properly.
      tags:
        - Application Observability
      x-amazon-apigateway-auth:
        type: AWS_IAM
      x-amazon-apigateway-integration:
        type: http_proxy
        httpMethod: "ANY"
        connectionId: "${vpcLinkId}"
        connectionType: VPC_LINK
        uri: "http://${loadBalancerDnsName}/api/check/health"
  /check/liveness:
    get:
      description:
        Performs a liveness probe to determine whether the runtime is working
        properly.
      operationId: getLiveness
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthStatus"
          description: The runtime is working properly.
      tags:
        - Application Observability
      x-amazon-apigateway-auth:
        type: AWS_IAM
      x-amazon-apigateway-integration:
        type: http_proxy
        httpMethod: "ANY"
        connectionId: "${vpcLinkId}"
        connectionType: VPC_LINK
        uri: "http://${loadBalancerDnsName}/api/check/liveness"
  /check/readiness:
    get:
      description:
        Performs a readiness probe to determine whether the runtime is
        able to accept requests.
      operationId: getReadiness
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthStatus"
          description: The runtime is able to accept requests.
      tags:
        - Application Observability
      x-amazon-apigateway-auth:
        type: AWS_IAM
      x-amazon-apigateway-integration:
        type: http_proxy
        httpMethod: "ANY"
        connectionId: "${vpcLinkId}"
        connectionType: VPC_LINK
        uri: "http://${loadBalancerDnsName}/api/check/readiness"
  /check/startup:
    get:
      description:
        Performs a startup probe to determine whether the runtime has completed
        startup.
      operationId: getStartup
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthStatus"
          description: The runtime has completed startup.
      tags:
        - Application Observability
      x-amazon-apigateway-auth:
        type: AWS_IAM
      x-amazon-apigateway-integration:
        type: http_proxy
        httpMethod: "ANY"
        connectionId: "${vpcLinkId}"
        connectionType: VPC_LINK
        uri: "http://${loadBalancerDnsName}/api/check/startup"
components:
  schemas:
    Failure:
      type: object
      properties:
        failureDetail:
          type: string
        messages:
          type: array
          items:
            type: string
    HealthCheckResult:
      type: object
      properties:
        component:
          type: string
        failure:
          $ref: "#/components/schemas/Failure"
        isHealthy:
          type: boolean
    HealthStatus:
      type: object
      properties:
        componentResults:
          type: array
          items:
            $ref: "#/components/schemas/HealthCheckResult"
        isSystemHealthy:
          type: boolean
